// Seed data for 12 patients
export const patientData = [
  {
    username: 'patient1',
    patientName: 'John Doe',
    age: 30,
    location: { city: 'City1', state: 'State1' },
    disease: [{ diseaseName: 'Flu', diseaseSeverity: 'moderate' }],
    income: 50000,
    contact: { phoneNo: '123-456-7890', email: 'john.doe@example.com' },
    Gender: 'Male',
    occupation: 'Engineer',
    insurance: {
      coverage_limit: 100000,
      remaining_balance: 50000,
      coverage_percentage: 50,
    },
    password: 'password1',
    avatar: 'avatar1.jpg',
    coverImage: 'cover1.jpg',
  },
  {
    username: 'patient2',
    patientName: 'Jane Smith',
    age: 25,
    location: { city: 'City2', state: 'State2' },
    disease: [{ diseaseName: 'Allergy', diseaseSeverity: 'minor' }],
    income: 40000,
    contact: { phoneNo: '987-654-3210', email: 'jane.smith@example.com' },
    Gender: 'Female',
    occupation: 'Teacher',
    insurance: {
      coverage_limit: 80000,
      remaining_balance: 60000,
      coverage_percentage: 75,
    },
    password: 'password2',
    avatar: 'avatar2.jpg',
    coverImage: 'cover2.jpg',
  },
  {
    username: 'patient3',
    patientName: 'Robert Johnson',
    age: 40,
    location: { city: 'City3', state: 'State3' },
    disease: [{ diseaseName: 'Hypertension', diseaseSeverity: 'major' }],
    income: 60000,
    contact: { phoneNo: '555-123-4567', email: 'robert.johnson@example.com' },
    Gender: 'Male',
    occupation: 'Accountant',
    insurance: {
      coverage_limit: 120000,
      remaining_balance: 80000,
      coverage_percentage: 66,
    },
    password: 'password3',
    avatar: 'avatar3.jpg',
    coverImage: 'cover3.jpg',
  },
  {
    username: 'patient4',
    patientName: 'Emily White',
    age: 28,
    location: { city: 'City4', state: 'State4' },
    disease: [{ diseaseName: 'Migraine', diseaseSeverity: 'moderate' }],
    income: 55000,
    contact: { phoneNo: '111-222-3333', email: 'emily.white@example.com' },
    Gender: 'Female',
    occupation: 'Graphic Designer',
    insurance: {
      coverage_limit: 90000,
      remaining_balance: 70000,
      coverage_percentage: 78,
    },
    password: 'password4',
    avatar: 'avatar4.jpg',
    coverImage: 'cover4.jpg',
  },
  {
    username: 'patient5',
    patientName: 'Michael Brown',
    age: 35,
    location: { city: 'City5', state: 'State5' },
    disease: [{ diseaseName: 'Diabetes', diseaseSeverity: 'major' }],
    income: 70000,
    contact: { phoneNo: '999-888-7777', email: 'michael.brown@example.com' },
    Gender: 'Male',
    occupation: 'Software Engineer',
    insurance: {
      coverage_limit: 110000,
      remaining_balance: 75000,
      coverage_percentage: 68,
    },
    password: 'password5',
    avatar: 'avatar5.jpg',
    coverImage: 'cover5.jpg',
  },
  {
    username: 'patient6',
    patientName: 'Sophia Turner',
    age: 32,
    location: { city: 'City6', state: 'State6' },
    disease: [{ diseaseName: 'Asthma', diseaseSeverity: 'minor' }],
    income: 48000,
    contact: { phoneNo: '555-987-6543', email: 'sophia.turner@example.com' },
    Gender: 'Female',
    occupation: 'Marketing Manager',
    insurance: {
      coverage_limit: 95000,
      remaining_balance: 60000,
      coverage_percentage: 63,
    },
    password: 'password6',
    avatar: 'avatar6.jpg',
    coverImage: 'cover6.jpg',
  },
  {
    username: 'patient7',
    patientName: 'Daniel Garcia',
    age: 45,
    location: { city: 'City7', state: 'State7' },
    disease: [{ diseaseName: 'Arthritis', diseaseSeverity: 'moderate' }],
    income: 75000,
    contact: { phoneNo: '123-789-4560', email: 'daniel.garcia@example.com' },
    Gender: 'Male',
    occupation: 'Business Analyst',
    insurance: {
      coverage_limit: 130000,
      remaining_balance: 90000,
      coverage_percentage: 69,
    },
    password: 'password7',
    avatar: 'avatar7.jpg',
    coverImage: 'cover7.jpg',
  },
  {
    username: 'patient8',
    patientName: 'Olivia Robinson',
    age: 27,
    location: { city: 'City8', state: 'State8' },
    disease: [{ diseaseName: 'Depression', diseaseSeverity: 'major' }],
    income: 60000,
    contact: { phoneNo: '777-888-9999', email: 'olivia.robinson@example.com' },
    Gender: 'Female',
    occupation: 'Psychologist',
    insurance: {
      coverage_limit: 100000,
      remaining_balance: 80000,
      coverage_percentage: 80,
    },
    password: 'password8',
    avatar: 'avatar8.jpg',
    coverImage: 'cover8.jpg',
  },
  {
    username: 'patient9',
    patientName: 'William Adams',
    age: 40,
    location: { city: 'City9', state: 'State9' },
    disease: [{ diseaseName: 'Chronic Pain', diseaseSeverity: 'major' }],
    income: 70000,
    contact: { phoneNo: '333-444-5555', email: 'william.adams@example.com' },
    Gender: 'Male',
    occupation: 'Physiotherapist',
    insurance: {
      coverage_limit: 120000,
      remaining_balance: 95000,
      coverage_percentage: 79,
    },
    password: 'password9',
    avatar: 'avatar9.jpg',
    coverImage: 'cover9.jpg',
  },
  {
    username: 'patient10',
    patientName: 'Ella Ward',
    age: 29,
    location: { city: 'City10', state: 'State10' },
    disease: [{ diseaseName: 'Insomnia', diseaseSeverity: 'minor' }],
    income: 55000,
    contact: { phoneNo: '666-555-4444', email: 'ella.ward@example.com' },
    Gender: 'Female',
    occupation: 'Writer',
    insurance: {
      coverage_limit: 90000,
      remaining_balance: 70000,
      coverage_percentage: 78,
    },
    password: 'password10',
    avatar: 'avatar10.jpg',
    coverImage: 'cover10.jpg',
  },
  {
    username: 'patient11',
    patientName: 'Henry Turner',
    age: 33,
    location: { city: 'City11', state: 'State11' },
    disease: [{ diseaseName: 'Allergy', diseaseSeverity: 'minor' }],
    income: 48000,
    contact: { phoneNo: '555-111-9999', email: 'henry.turner@example.com' },
    Gender: 'Male',
    occupation: 'Chef',
    insurance: {
      coverage_limit: 95000,
      remaining_balance: 60000,
      coverage_percentage: 63,
    },
    password: 'password11',
    avatar: 'avatar11.jpg',
    coverImage: 'cover11.jpg',
  },
  {
    username: 'patient12',
    patientName: 'Ava King',
    age: 26,
    location: { city: 'City12', state: 'State12' },
    disease: [{ diseaseName: 'Anxiety', diseaseSeverity: 'minor' }],
    income: 45000,
    contact: { phoneNo: '123-789-4560', email: 'ava.king@example.com' },
    Gender: 'Female',
    occupation: 'Artist',
    insurance: {
      coverage_limit: 85000,
      remaining_balance: 55000,
      coverage_percentage: 65,
    },
    password: 'password12',
    avatar: 'avatar12.jpg',
    coverImage: 'cover12.jpg',
  },
  // Continue adding data for other patients...
];